using Akka.Event;
using Akka.Streams;
using Akka.Streams.Stage;
using TurboHttp.Internal;
using TurboHttp.Protocol.Http11;
using TurboHttp.Protocol.Http3;

namespace TurboHttp.Streams.Stages.Features;

internal sealed class
    ConnectionReuseStage : GraphStage<FanOutShape<HttpResponseMessage, HttpResponseMessage, IOutputItem>>
{
    private readonly bool _bodyFullyConsumed;

    private readonly Inlet<HttpResponseMessage> _in = new("ConnectionReuse.In");
    private readonly Outlet<HttpResponseMessage> _outResponse = new("ConnectionReuse.Out.Response");
    private readonly Outlet<IOutputItem> _outSignal = new("ConnectionReuse.Out.Signal");

    public override FanOutShape<HttpResponseMessage, HttpResponseMessage, IOutputItem> Shape { get; }


    public ConnectionReuseStage(bool bodyFullyConsumed = true)
    {
        _bodyFullyConsumed = bodyFullyConsumed;
        Shape = new FanOutShape<HttpResponseMessage, HttpResponseMessage, IOutputItem>(
            _in, _outResponse, _outSignal);
    }

    protected override GraphStageLogic CreateLogic(Attributes inheritedAttributes)
        => new Logic(this);

    private sealed class Logic : GraphStageLogic
    {
        private readonly ConnectionReuseStage _stage;
        private HttpResponseMessage? _pendingResponse;
        private ConnectionReuseItem? _pendingSignal;
        private bool _responseOutletDemand;
        private bool _signalOutletDemand;
        private bool _isHttp10;

        public Logic(ConnectionReuseStage stage) : base(stage.Shape)
        {
            _stage = stage;

            SetHandler(stage._in,
                onPush: () =>
                {
                    var response = Grab(stage._in);
                    var decision = EvaluateReuse(response, stage._bodyFullyConsumed);

                    var endpoint = response.RequestMessage is { RequestUri: not null, Version: not null }
                        ? RequestEndpoint.FromRequest(response.RequestMessage)
                        : RequestEndpoint.Default;

                    Log.Debug("ConnectionReuseStage: onPush response status={0}, canReuse={1}, endpoint={2}:{3}",
                        (int)response.StatusCode, decision.CanReuse, endpoint.Host, endpoint.Port);

                    _pendingResponse = response;
                    _isHttp10 = response.Version is { Major: 1, Minor: 0 };

                    // HTTP/1.0: skip feedback signal — ExtractOptionsStage emits ConnectItem
                    // unconditionally for HTTP/1.0 because the protocol always closes the
                    // connection after each response (RFC 9110 §9.2.1).
                    // Connection reuse does not apply; therefore, the feedback signal is not needed.
                    //
                    // WARNING: Skipping the signal does NOT satisfy the signal outlet demand.
                    // In Akka.Streams, demand is only satisfied by a downstream Pull. Since no
                    // signal is ever emitted, the signal outlet is never pulled, and
                    // _signalOutletDemand remains false. This creates a permanent deadlock in
                    // TryPullIfReady() unless the method is aware of HTTP/1.0's signal-skip
                    // behavior (see TryPullIfReady() for details).
                    if (!_isHttp10)
                    {
                        _pendingSignal = ConnectionReuseItem.Rent(endpoint, decision);
                    }
                    else
                    {
                        Log.Debug("ConnectionReuseStage: H10 bypass — skipping feedback signal for {0}:{1}",
                            endpoint.Host, endpoint.Port);
                    }

                    // Signal MUST be pushed before response so that the feedback path
                    // (ExtractOptionsStage._needsReconnect) is set before a redirect/retry
                    // request generated by RedirectBidiStage/RetryBidiStage can reach
                    // ExtractOptionsStage.In.  In a fused graph, Push propagates
                    // synchronously — pushing the response first would let the redirect
                    // request arrive before _needsReconnect is true, skipping ConnectItem
                    // emission and causing a deadlock (HTTP/1.0 reconnection).
                    TryPushSignal();
                    TryPushResponse();
                },
                onUpstreamFinish: () =>
                {
                    if (_pendingResponse is null && _pendingSignal is null)
                    {
                        CompleteStage();
                    }
                },
                onUpstreamFailure: ex =>
                {
                    // Absorb the failure (don't crash the pipeline) but complete the stage
                    // so downstream stages can drain and the substream shuts down cleanly.
                    Log.Warning("ConnectionReuseStage: Upstream failure absorbed: {0}", ex.Message);
                    CompleteStage();
                });

            SetHandler(stage._outResponse,
                onPull: () =>
                {
                    _responseOutletDemand = true;
                    TryPushResponse();
                    TryPullIfReady();
                },
                onDownstreamFinish: _ => CompleteStage());

            SetHandler(stage._outSignal,
                onPull: () =>
                {
                    _signalOutletDemand = true;
                    TryPushSignal();
                    TryPullIfReady();
                },
                onDownstreamFinish: _ => CompleteStage());
        }

        /// <summary>
        /// Dispatches to the appropriate reuse evaluator based on HTTP version.
        /// HTTP/3+ responses use <see cref="Http3ConnectionReuseEvaluator"/> (RFC 9114 §3.3);
        /// all others use <see cref="ConnectionReuseEvaluator"/> (RFC 9112 §9).
        /// </summary>
        private static ConnectionReuseDecision EvaluateReuse(
            HttpResponseMessage response, bool bodyFullyConsumed)
        {
            if (response.Version.Major >= 3)
            {
                return EvaluateHttp3Reuse(response);
            }

            return ConnectionReuseEvaluator.Evaluate(
                response, response.Version, bodyFullyConsumed);
        }

        /// <summary>
        /// Evaluates HTTP/3 connection reuse via <see cref="Http3ConnectionReuseEvaluator"/>.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <b>serverCertificate</b>: The server's TLS certificate is not available in the
        /// <see cref="HttpResponseMessage"/> context. It lives in the QUIC connection state
        /// managed by <c>QuicClientProvider</c>. To enable cross-origin coalescing, the
        /// certificate would need to be threaded through the pipeline (e.g. via
        /// <see cref="HttpRequestOptions"/> or a custom property on the response).
        /// Currently passed as <c>null</c>, which means cross-origin reuse is conservatively
        /// denied — same-origin reuse still works correctly.
        /// </para>
        /// <para>
        /// <b>isGoingAway</b>: The GOAWAY state is tracked by <c>Http30ConnectionStage</c>
        /// and is not propagated to downstream stages. To support GOAWAY-aware reuse
        /// decisions, <c>Http30ConnectionStage</c> would need to signal going-away state
        /// via the response (e.g. a custom header or <see cref="HttpRequestOptions"/> entry).
        /// Currently passed as <c>false</c>; GOAWAY handling remains at the connection stage level.
        /// </para>
        /// </remarks>
        private static ConnectionReuseDecision EvaluateHttp3Reuse(HttpResponseMessage response)
        {
            var uri = response.RequestMessage?.RequestUri;

            var scheme = uri?.Scheme ?? "https";
            var host = uri?.Host ?? string.Empty;
            var port = uri?.Port ?? 443;

            // serverCertificate: not available in response context — see remarks.
            // isGoingAway: not available in response context — see remarks.
            var h3Decision = Http3ConnectionReuseEvaluator.Evaluate(
                connectionScheme: scheme,
                connectionHost: host,
                connectionPort: port,
                targetScheme: scheme,
                targetHost: host,
                targetPort: port,
                serverCertificate: null,
                isGoingAway: false);

            // Bridge Http3ConnectionReuseDecision → ConnectionReuseDecision
            return h3Decision.CanReuse
                ? ConnectionReuseDecision.KeepAlive(h3Decision.Reason)
                : ConnectionReuseDecision.Close(h3Decision.Reason);
        }

        private void TryPushResponse()
        {
            if (_pendingResponse is null || !_responseOutletDemand)
            {
                return;
            }

            var response = _pendingResponse;
            _pendingResponse = null;
            _responseOutletDemand = false;

            Push(_stage._outResponse, response);
            TryPullIfReady();
        }

        private void TryPushSignal()
        {
            if (_pendingSignal is null || !_signalOutletDemand)
            {
                return;
            }

            var signal = _pendingSignal;
            _pendingSignal = null;
            _signalOutletDemand = false;

            Log.Debug("ConnectionReuseStage: pushing signal canReuse={0}, key={1}:{2}",
                signal.Decision.CanReuse, signal.Key.Host, signal.Key.Port);
            Push(_stage._outSignal, signal);
            TryPullIfReady();
        }

        private void TryPullIfReady()
        {
            Log.Debug("ConnectionReuseStage.TryPullIfReady: entry — pendingResponse={0}, pendingSignal={1}, responseDemand={2}, signalDemand={3}, isHttp10={4}",
                _pendingResponse is not null, _pendingSignal is not null, _responseOutletDemand, _signalOutletDemand, _isHttp10);

            // Pull next element only once all pending items have been served
            if (_pendingResponse is not null || _pendingSignal is not null)
            {
                Log.Debug("ConnectionReuseStage.TryPullIfReady: early exit — still have pending items");
                return;
            }

            // PROTOCOL-SPECIFIC DEMAND CHECK:
            // For HTTP/1.0, the signal outlet is intentionally NOT fed because connection reuse
            // does not apply to HTTP/1.0 (the protocol mandates connection-close semantics per
            // RFC 9110 §9.2.1). ExtractOptionsStage handles reconnection directly via HTTP/1.0
            // protocol detection.
            //
            // Since no signal is ever emitted for HTTP/1.0, the signal outlet is never pulled
            // and _signalOutletDemand never becomes true. To avoid a permanent deadlock, we
            // conditionally check _signalOutletDemand only for HTTP/1.1+ protocols.
            //
            // For HTTP/1.0: check only _responseOutletDemand
            // For HTTP/1.1+: check both _responseOutletDemand AND _signalOutletDemand
            // (the signal outlet is actively consumed by the feedback path)

            // Check response demand (required for all protocols)
            if (!_responseOutletDemand)
            {
                Log.Debug("ConnectionReuseStage.TryPullIfReady: early exit — no response demand");
                return;
            }

            // Check signal demand only for HTTP/1.1+ (for HTTP/1.0, skip this check)
            if (!_isHttp10 && !_signalOutletDemand)
            {
                Log.Debug("ConnectionReuseStage.TryPullIfReady: early exit — insufficient signal demand for HTTP/1.1+");
                return;
            }

            Log.Debug("ConnectionReuseStage.TryPullIfReady: both demands satisfied, checking upstream state");

            if (IsClosed(_stage._in))
            {
                Log.Debug("ConnectionReuseStage.TryPullIfReady: upstream is closed, completing stage");
                CompleteStage();
            }
            else if (!HasBeenPulled(_stage._in))
            {
                Log.Debug("ConnectionReuseStage.TryPullIfReady: pulling upstream for next response");
                Pull(_stage._in);
            }
            else
            {
                Log.Debug("ConnectionReuseStage.TryPullIfReady: upstream already pulled");
            }
        }
    }
}