name: Build & Test

permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "notes/**"
      - "*.md"
      - ".github/workflows/docs.yml"
      - ".github/workflows/commitlint.yml"
      - ".github/workflows/codeql.yml"
      - ".github/workflows/release.yml"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "notes/**"
      - "*.md"
      - ".github/workflows/docs.yml"
      - ".github/workflows/commitlint.yml"
      - ".github/workflows/codeql.yml"
      - ".github/workflows/release.yml"

jobs:
  build:
    uses: Leberkas-org/template.pipeline.github/.github/workflows/build-test.yml@v0
    with:
      solution-path: TurboHTTP.slnx
      extra-apt-packages: libmsquic
      locked-mode: true
