name: PR & Commit Lint

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches: ["main"]
    types: [opened, edited, synchronize]

jobs:
  lint:
    uses: Leberkas-org/template.pipeline.github/.github/workflows/commitlint.yml@v0
