name: Release & Publish

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  release:
    uses: Leberkas-org/template.pipeline.github/.github/workflows/release.yml@v0
    with:
      nuget-publish: true
      docs-deploy: true
      solution-path: ./src/TurboHTTP.slnx
      docs-build-command: "npx likec4 export png --output public/diagrams ./likec4 || true && npm run build"
    secrets:
      nuget-api-key: ${{ secrets.NUGET_SECRET }}
